cursodjango/base/urls.py
from django.urls import path

from cursodjango.base.views import home


app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

cursodjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursodjango.base.urls')),
    path('preview/', include('cursodjango.vpreview.urls')),
]
if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

cursodjango/vpreview/urls.py
from django.urls import path

from cursodjango.vpreview.views import video, indice

app_name = 'vpreview'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

cursodjango/base/models.py
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Username and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

cursodjango/vpreview/models.py
# from django.db import models

# Create your models here.

cursodjango/base/views.py
# from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def home(request):
    # return HttpResponse('<html><body>CURSO DJANGO</html></body>', content_type='text/html')
    return render(request, 'base/home.html')

cursodjango/vpreview/views.py
from django.urls import reverse
from django.shortcuts import render


class Video:
    def __init__(self, slug, titulo, vimeo_id, vimeo_titulo):
        self.slug = slug
        self.titulo = titulo
        self.vimeo_id = vimeo_id
        self.vimeo_titulo = vimeo_titulo

    def get_absolute_url(self):
        return reverse('vpreview:video', args=(self.slug,))


videos = [
        Video(
            'preview',
            'Preview do Curso de Python e Django:',
            1043031414,
            'Python-preview-course'
        ),
        Video(
            'variaveis',
            'Curso de Python e Django: Variáveis:',
            1043327662,
            'Variáveis-em-Python'
        )
    ]

videos_dct = {v.slug: v for v in videos}


def indice(request):

    return render(request, 'vpreview/indice.html', context={'videos': videos})


def video(request, slug):
    video = videos_dct[slug]
    return render(request, 'vpreview/video.html', context={'video': video})


#  ESTRUTURA HARDCODE PARA EXTRAIR DICIONÁRIOS DE UMA LISTA DE DICIONÁRIOS:
# videos = [
#         {
#             'slug': 'preview',
#             'titulo': 'Preview do Curso de Python e Django:',
#             'vimeo_id': 1043031414,
#             'vimeo_titulo': 'Python-preview-course'
#         },
#         {
#             'slug': 'variaveis',
#             'titulo': 'Curso de Python e Django: Variáveis:',
#             'vimeo_id': 1043327662,
#             'vimeo_titulo': 'Variáveis-em-Python'
#         }
#     ]
#
# videos_dct = {dct['slug']: dct for dct in videos}


# ESTRUTURA HARDCODE:
# def video(request, slug):
#     videos = {
#         'preview': {
#             'slug': 'preview',
#             'titulo': 'Preview do Curso de Python e Django:',
#             'vimeo_id': 1043031414,
#             'vimeo_titulo': 'Python-preview-course'
#         },
#         'variaveis': {
#             'slug': 'variaveis',
#             'titulo': 'Curso de Python e Django: Variáveis:',
#             'vimeo_id': 1043327662,
#             'vimeo_titulo': 'Variáveis-em-Python'
#         }
#     }
#     video = videos[slug]
#     return render(request, 'vpreview/video.html', context={'video': video})

cursodjango/base/templates/base/base.html
<!doctype html>
{% load static %}
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Página exemplo de um curso de django">
        <meta name="author" content="Michel Alves">
        <title>{% block title %}Curso de Python e Django{% endblock title %}</title>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
            crossorigin="anonymous"
        >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="icon" type="image/png" href="{% static 'img/hippo-icon.png' %}">
    </head>
    <body>
        <div class="container-page">
            <div class="container-fluid">

                <div class="row mb-5 my-3 fw-bold">
                    <div class="col-md-12">
                        <nav class="navbar navbar-expand-lg" style="background-color: linear-gradient(45deg, #ffffff, #0a4416);">
                            <div class="container-fluid">
                                <a class="navbar-brand text-light" href="{% url 'base:home' %}">
                                    <img
                                        src="{% static 'img/hippo_logo.png' %}"
                                        class="img-fluid rounded"
                                        alt="django-picture"
                                        style="width: 140px;"
                                    >
                                </a>
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--                                        <li class="nav-item">-->
<!--                                            <a class="nav-link active text-light" aria-current="page" href="#">Home</a>-->
<!--                                        </li>-->
<!--                                        <li class="nav-item">-->
<!--                                            <a class="nav-link text-light" href="#">Link</a>-->
<!--                                        </li>-->
<!--                                        <li class="nav-item dropdown">-->
<!--                                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                                            Dropdown-->
<!--                                            </a>-->
<!--                                            <ul class="dropdown-menu">-->
<!--                                                <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--                                                <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--                                                <li><hr class="dropdown-divider"></li>-->
<!--                                                <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--                                            </ul>-->
<!--                                        </li>-->
<!--                                        <li class="nav-item">-->
<!--                                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
<!--                                        </li>-->
                                    </ul>
                                    <!-- <form class="d-flex" role="search">
                                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                        <button class="btn btn-success" type="submit">Search</button>
                                    </form> -->
                                    <div>
                                        <button type="button" class="btn btn-success">Login</button>
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>


                {% block body %} {% endblock body %}


            </div>
        </div>


        <footer class="bg-success d-flex justify-content-end align-items-center">
            <div class="d-flex justify-content-end align-items-center">
                <p class="mt-3">Página criada pelo grupo:</p>
                <img
                    src="{% static 'img/hippo_logo.png' %}"
                    class="img-fluid rounded"
                    alt="django-picture"
                    style="width: 100px;"
                >
                <p class="mt-3 me-5">{% now 'y' %}</p>
            </div>
        </footer>


        <script 
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
            crossorigin="anonymous"
        ></script>

    </body>
</html>

cursodjango/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Curso de Python e Django - Home{% endblock title %}

{% block body %}

    <div class="row my-5 mb-5">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2 class="blink">
                    NOVO CURSO!!!
                </h2>
                <div class="mx-1 my-5 m-sm-5">
                    <img src="{% static 'img/python-django.png' %}" class="img-fluid rounded mx-auto d-block" alt="django-picture" style="width: 900px;">
                </div>
                <h2 class="text-center fw-bold">
                    Aprenda Python e Django: Domine o Desenvolvimento Web!
                </h2>
                <p class="text-center fs-5">
                    Quer aprender a criar aplicações web incríveis e conquistar o mercado de tecnologia?
                </p>
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner text-warning">
                        <div class="carousel-item active">
                            <h2 class="text-center">100% online e prático</h2>
                        </div>
                        <div class="carousel-item">
                            <h2 class="text-center">Aprenda desde o básico até o avançado</h2>
                        </div>
                        <div class="carousel-item">
                            <h2 class="text-center">Ideal para iniciantes e quem já programa</h2>
                        </div>
                        <div class="carousel-item">
                            <h2 class="text-center">Certificado reconhecido ao final</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6 px-3 text-dark">
            <img alt="instrutor-picture" src="{% static 'img/instrutor.png' %}" class="border border-3 border-success img-fluid rounded mx-auto d-block" />
            <dl>
                <dt>
                    <h3 class="my-3">
                        Conheça o seu Instrutor: <span class="text-warning">Carlos Mendes</span>
                    </h3>
                </dt>
                <dd>
                    Carlos Mendes é o instrutor ideal para guiar você no universo do desenvolvimento web com Python e Django. Com mais de 10 anos de experiência na área, ele já trabalhou em grandes empresas de tecnologia e foi responsável por desenvolver sistemas utilizados por milhares de usuários em todo o Brasil.
                </dd>
                <dd>
                    Além de programador, ele é apaixonado por ensinar e é autor de diversos tutoriais sobre desenvolvimento web.
                </dd>
                <dd>
                    Carlos também é fluente em inglês e está sempre de olho nas tendências globais de tecnologia para trazer o melhor conteúdo para seus alunos.
                </dd>
                <dd>
                    Com Carlos Mendes, você não apenas aprende a programar, mas também descobre como se destacar no mercado de trabalho e criar soluções inovadoras.
                </dd>
            </dl>
        </div>

        <div class="col-md-6">
            <div class="mx-sm-5 px-sm-4">
                <div class="grid gap-3 ">
                    <div class="p-2 g-col-6 text-warning fs-3">O que você vai aprender:</div>
                    <div class="p-2 g-col-6 fs-5"><span class="text-success me-3"><i class="fab fa-python"></i></span>Fundamentos do Python</div>
                    <div class="p-2 g-col-6 fs-5"><span class="text-success me-3"><i class="fab fa-python"></i></span>Criação de aplicações web com Django</div>
                    <div class="p-2 g-col-6 fs-5"><span class="text-success me-3"><i class="fab fa-python"></i></span>Banco de dados e autenticação de usuários</div>
                    <div class="p-2 g-col-6 fs-5"><span class="text-success me-3"><i class="fab fa-python"></i></span>Deploy de aplicações para a web</div>
                    <div class="p-2 g-col-6 fs-5">E muito mais...</div>
                </div>
                <div class="grid gap-3 my-5 border border-3 rounded border-warning p-4">
                    <div class="p-2 g-col-6 fs-5 text-warning">
                        <span class="text-warning ms-1 me-2"><i class="far fa-calendar"></i></span>
                        Início das aulas:
                        <span class="text-light">2025</span>
                    </div>
                    <div class="p-2 g-col-6 fs-5 text-warning">
                        <span class="text-warning me-1"><i class="fas fa-laptop"></i></span>
                        Formato:
                        <span class="text-light">Online (ao vivo / gravado)</span>
                    </div>
                    <div class="p-2 g-col-6 fs-5 text-warning">
                        <span class="text-warning ms-2 me-2"><i class="fas fa-dollar-sign"></i></span>
                        Investimento:
                        <span class="text-danger fw-bold">Somente R$ 199,00</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row my-5 mb-5">
        <div class="col-md-12">
            <p class="fs-2 text-center text-light fw-bold">Em breve, uma prévia do curso!</p>
            <div class="d-grid gap-2 col-sm-4 mx-auto my-3">
<!--                <a href="{{ video.get_absolute_url }}" class="btn btn-success">-->
<!--                    {{ video.titulo | default:'Faltando título' }}-->
<!--                </a>-->
            </div>
        </div>
    </div>


    {% include 'base/subscribe.html' %}

{% endblock body %}

cursodjango/base/templates/base/subscribe.html
{% load static %}

<div class="row my-5 mb-5">
    <div class="col-md-12">
        <p class="fs-2 text-center text-success fw-bold">Não perca tempo!</p>
        <p class="fs-3 text-center text-dark">Inscreva-se agora e dê o primeiro passo para sua carreira como desenvolvedor web.</p>
    </div>
    <div class="d-grid gap-2 col-sm-4 mx-auto my-3">
        <button type="button" class="btn btn-warning" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">Entrar na Lista de Espera</button>
    </div>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item border border-0 rounded">
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-warning-subtle">
                    <form class="row gy-2 gx-3 align-items-center justify-content-center" action="https://onrender.us7.list-manage.com/subscribe/post" method="POST">

                        <!-- people should not fill these in and expect good things -->
                        <div class="field-shift" aria-label="Please leave the following three fields empty" aria-hidden="true">
                            <label for="b_name">Name: </label>
                            <input type="text" name="b_name" tabindex="-1" value="" placeholder="Freddie" id="b_name">

                            <label for="b_email">Email: </label>
                            <input type="email" name="b_email" tabindex="-1" value="" placeholder="youremail@gmail.com" id="b_email">

                            <label for="b_comment">Comment: </label>
                            <textarea name="b_comment" tabindex="-1" placeholder="Please comment" id="b_comment"></textarea>
                        </div>

                        <input type="hidden" name="u" value="f514587aea3e8ace1dc87fd04">
                        <input type="hidden" name="id" value="9c1f3dceb3">

                        <div class="col-auto">
                            <label class="visually-hidden" for="MERGE1">Name</label>
                            <input type="text" name="MERGE1" id="MERGE1" size="25" value="" class="form-control" placeholder="Seu Nome:">
                        </div>
                        <div class="col-auto">
                            <label class="visually-hidden" for="MERGE0">Email</label>
                            <div class="input-group">
                                <div class="input-group-text">@</div>
                                <input type="email" autocapitalize="off" autocorrect="off" name="MERGE0" id="MERGE0" size="25" value="" class="form-control" placeholder="Seu Email:">
                            </div>
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-success" name="submit">Inscrever-se</button>
                        </div>
                        <input type="hidden" name="ht" value="dc3a73315201022515c2e6747f5f7b4f63413348:MTczNTM2MjY3MS4yODUy">
                        <input type="hidden" name="mc_signupsource" value="hosted">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

cursodjango/vpreview/templates/vpreview/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Curso de Python e Django - Preview{% endblock title %}

{% block body %}

    <div class="row my-5 mb-5">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Lista de videos preview:</h1>
                <div class="list-group list-group-numbered">
                    {% for video in videos %}
                        <a href="{{ video.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-success">
                            {{ video.titulo | default:'Faltando título' }}
                        </a>
                        {% empty %}
                            <a href="#" class="list-group-item list-group-item-action list-group-item-danger">
                                Não foi encontrado nenhum video!
                            </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {% include 'base/subscribe.html' %}

{% endblock body %}

cursodjango/vpreview/templates/vpreview/video.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Curso de Python e Django - Preview{% endblock title %}

{% block body %}

    <div class="row my-5 mb-5">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>{{ video.titulo | default:'Faltando título' }}</h1>
            </div>
        </div>
    </div>

    <div class="row my-5 mb-5">
        <div class="col-md-12">
            <div class="">
                <div style="padding:56.25% 0 0 0;position:relative;">
                    <iframe src="https://player.vimeo.com/video/{{video.vimeo_id}}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
                            style="position:absolute;top:0;left:0;width:100%;height:100%;"
                            title="{{ video.vimeo_titulo }}">
                    </iframe>
                </div>
                <script src="https://player.vimeo.com/api/player.js"></script>
            </div>
        </div>
    </div>

    {% include 'base/subscribe.html' %}

{% endblock body %}